apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
    component: myapp
spec:
  ports:
    - type: NodePort
    - name: "3003"
      port: 3003
      targetPort: 3003
  selector:
    app: app
    component: myapp

