apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-claim0
#  creationTimestamp: null
  labels:
    type: local
#    app: app-claim0
#    component: myapp

spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
#status: {}
