apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
#  labels:
#   app: app
#    component: myapp
spec:
  volumeName: pv-app
#  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: app
      component: myapp
#status: {}
