apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-claim0
#  creationTimestamp: null
#  labels:
#    app: app-claim0
#    component: myapp

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
#status: {}
