apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-claim0
  labels:
    app: app
    component: myapp
spec:
  volumeName: task-pv-volume
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      type: local
#status: {}
