apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
#  creationTimestamp: null
  labels:
    type: local
#    app: tutorial-volume
#    component: myapp

spec:
  volumeName: pv-db
#  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: db
      component: myapp
#status: {}
