apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
    component: myapp
spec:
  type: NodePort
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    app: db
    component: myapp

