apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-app
  labels:
#   type: local
    app: app
    component: myapp
spec:
#  storageClassName: local-storage
  capacity:
    storage: 300Mi
#  local:
#    path: /data/myapp
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/app"

