apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
#  labels:
#    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 300Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"