apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
#    app: app
#    component: myapp
spec:
#  storageClassName: ""
  capacity:
    storage: 300Mi
#  local:
#    path: /data/myapp
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
#    path: "/data/myapp"

