apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
#    app: app
#    component: myapp
spec:
#  storageClassName: ""
  capacity:
    storage: 300Mi
#  local:
#    path: /data/myapp
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/data"
#    path: "/data/myapp"
#  nodeAffinity:
#    required:
#      nodeSelectorTerms:
#        - matchExpressions:
#            - key: kubernetes.io/app
#              operator: In
#              values:
#                - app
