apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
#    io.kompose.service: tutorial-volume
    app: tutorial-volume
    component: myapp
  name: tutorial-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
