apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tutorial-volume
#  creationTimestamp: null
#  labels:
#    app: tutorial-volume
#    component: myapp

spec:
  storageClassName: fast
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
#status: {}
