apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tutorial-volume
#  creationTimestamp: null
  labels:
    type: local
#    app: tutorial-volume
#    component: myapp

spec:
#  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
#status: {}
